'use strict';
const SECONDS=30, TOTAL=SLIDES.length+1;
const MAX_URL='https://max.ru/file_uploads_bot?startapp=9ab17b8e-fda4-428b-a5b3-5d77689dabbe';
const STORE='internet-services-11-v1';
const $=s=>document.querySelector(s);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let storageOK=true;
function read(key){try{return JSON.parse(localStorage.getItem(STORE+key)||'null')}catch{return null}}
function save(key,value){try{localStorage.setItem(STORE+key,JSON.stringify(value));return true}catch{storageOK=false;return false}}
function remove(key){try{localStorage.removeItem(STORE+key)}catch{storageOK=false}}
function validName(name){return typeof name==='string'&&name.length<=50&&/^[\p{L}\p{M}]+(?:[ '\u2019-][\p{L}\p{M}]+)*$/u.test(name)}
function validAnswers(a){return Array.isArray(a)&&a.length<=QUESTIONS.length&&a.every(v=>Number.isInteger(v)&&v>=-1&&v<=3)}
function validIdentity(r){return r&&validName(r.first)&&validName(r.last)}
let attempt=read('-attempt');
if(!(validIdentity(attempt)&&validAnswers(attempt.answers)&&attempt.answers.length<10&&Number.isFinite(attempt.deadline)&&attempt.deadline>0)){attempt=null;remove('-attempt')}
let result=read('-result');
if(!(validIdentity(result)&&validAnswers(result.answers)&&result.answers.length===10&&Number.isFinite(result.completedAt))){result=null}
let position=0, clockID=null, locked=false, lastTimedOut=false;
const sections=[...new Set(SLIDES.map(s=>s.section)),'Самопроверка'];
$('#chapters').innerHTML=sections.map((s,i)=>`<button type="button" data-section="${i}"><span>${String(i+1).padStart(2,'0')}</span>${s}</button>`).join('');
$('#chapters').addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(!b)return;const index=Number(b.dataset.section);go(index===sections.length-1?SLIDES.length:SLIDES.findIndex(s=>s.section===sections[index]));$('#chapters').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false')});
$('.menu-toggle').addEventListener('click',()=>{$('#chapters').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',String($('#chapters').classList.contains('open')))});
function go(n){if(attempt&&position===SLIDES.length)return;position=Math.max(0,Math.min(TOTAL-1,n));location.hash=position===SLIDES.length?'test':`slide-${position+1}`;render();$('#main').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'})}
function fromHash(){const h=location.hash;const n=h==='#test'?SLIDES.length:Number(h.replace('#slide-',''))-1;if(attempt){position=SLIDES.length}else{position=Number.isInteger(n)&&n>=0&&n<TOTAL?n:0}render()}
window.addEventListener('hashchange',fromHash);
$('#previous').addEventListener('click',()=>go(position-1));$('#next').addEventListener('click',()=>go(position+1));
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||position===SLIDES.length||e.target.closest('input,button,select,textarea,summary,a'))return;if(e.key==='ArrowRight'){e.preventDefault();go(position+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(position-1)}});
let touchStart=null;
$('#slide').addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStart=[t.clientX,t.clientY]},{passive:true});
$('#slide').addEventListener('touchend',e=>{if(!touchStart||e.target.closest('button,a,input'))return;const t=e.changedTouches[0],dx=t.clientX-touchStart[0],dy=t.clientY-touchStart[1];if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.7)go(position+(dx<0?1:-1));touchStart=null},{passive:true});
function render(){const isQuiz=position===SLIDES.length;const s=isQuiz?null:SLIDES[position];$('#section-label').textContent=isQuiz?'Самопроверка':s.section;$('#page-label').textContent=`${String(position+1).padStart(2,'0')} / ${TOTAL}`;$('#lesson-progress-fill').style.width=`${(position+1)/TOTAL*100}%`;$('#slide').hidden=isQuiz;$('#quiz').hidden=!isQuiz;$('#previous').disabled=position===0||!!attempt;$('#next').hidden=isQuiz;$('.keyboard-hint').hidden=isQuiz;$('#chapters').querySelectorAll('button').forEach((b,i)=>{const active=sections[i]===(isQuiz?'Самопроверка':s.section);b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');b.disabled=!!attempt});if(!isQuiz){$('#slide').innerHTML=position===0?s.html:`<p class="eyebrow">${escapeHTML(s.section)}</p><h2>${s.title}</h2>${s.html}`;$('#source-line').textContent=`Источник: ${s.source}. А — «Сервисы Интернета, 11 класс»; Б — «Виды деятельности в сети Интернет». Номера обозначают слайды презентаций.`}else{$('#source-line').textContent='Все вопросы составлены по двум презентациям урока. Таймер и шкала оценивания установлены для этой самопроверки.';renderQuiz()}document.title=`${isQuiz?'Самопроверка':s.title} · Информатика, 11 класс`}
function renderQuiz(){if(attempt){showQuestion();startClock()}else if(result){showResult()}else{showStart()}}
function showStart(){clearInterval(clockID);$('#quiz').innerHTML=`<p class="eyebrow">Самопроверка / 10 вопросов</p><h2>Проверим, что ты запомнил</h2><p class="lead">Введи имя и фамилию. Они появятся в карточке результата для учителя.</p><div class="quiz-rules"><p><strong>30 секунд на каждый вопрос.</strong> Выбери один ответ и нажми «Ответить». Вернуться к предыдущему вопросу нельзя.</p><p>Когда время истечёт, вопрос засчитается без ответа и откроется следующий. Обновление страницы не сбрасывает таймер.</p><p><strong>Шкала:</strong> 9–10 баллов — «5»; 7–8 — «4»; 5–6 — «3»; 0–4 — «2». За правильный ответ — 1 балл.</p></div><form id="start-form"><div class="name-fields"><label for="first-name">Имя<input id="first-name" name="first" autocomplete="given-name" maxlength="50" required placeholder="Например, Анна"></label><label for="last-name">Фамилия<input id="last-name" name="last" autocomplete="family-name" maxlength="50" required placeholder="Например, Иванова"></label></div><p id="name-error" class="error" role="alert"></p><p class="fine">Имя, фамилия и результат сохраняются только в этом браузере на этом устройстве. Результат самопроверки можно пройти заново.</p><button class="button primary" type="submit">Начать тест →</button></form>`;$('#start-form').addEventListener('submit',e=>{e.preventDefault();const first=$('#first-name').value.trim().replace(/\s+/g,' '),last=$('#last-name').value.trim().replace(/\s+/g,' ');if(!validName(first)||!validName(last)){$('#name-error').textContent='Введи имя и фамилию буквами. Допускаются пробел, дефис и апостроф.';return}attempt={first,last,answers:[],deadline:Date.now()+SECONDS*1000};result=null;remove('-result');save('-attempt',attempt);lastTimedOut=false;render()})}
function showQuestion(){if(!attempt)return;const i=attempt.answers.length,q=QUESTIONS[i];$('#quiz').innerHTML=`<div class="quiz-head"><span class="eyebrow" style="margin:0">Вопрос ${i+1} из 10</span><span id="timer" class="timer" role="timer" aria-label="Осталось времени">30 с</span></div>${lastTimedOut?'<p class="feedback" role="status">Время предыдущего вопроса истекло. Он засчитан без ответа.</p>':''}<h2 id="question-title">${q.q}</h2><form id="answer-form"><fieldset class="answers" aria-labelledby="question-title"><legend>Выбери один ответ</legend>${q.a.map((a,j)=>`<label class="answer"><input type="radio" name="answer" value="${j}" required><span>${a}</span></label>`).join('')}</fieldset><div class="quiz-action"><span class="fine">${escapeHTML(attempt.first)} ${escapeHTML(attempt.last)}</span><button class="button primary" type="submit" id="submit-answer" disabled>${i===9?'Завершить тест':'Ответить →'}</button></div></form>${storageOK?'':'<p class="fine error">Браузер не разрешил сохранение. Не закрывай страницу до завершения теста и скачай результат.</p>'}`;$('#answer-form').addEventListener('change',()=>{$('#submit-answer').disabled=false});$('#answer-form').addEventListener('submit',e=>{e.preventDefault();const selected=$('input[name="answer"]:checked');if(selected)answer(Number(selected.value))});$('#announcer').textContent=`Вопрос ${i+1} из 10. ${q.q}`;updateTimer()}
function answer(value){if(!attempt||locked)return;locked=true;const now=Date.now();if(now>=attempt.deadline){locked=false;tick();return}attempt.answers.push(value);lastTimedOut=false;if(attempt.answers.length===10){finish()}else{attempt.deadline=now+SECONDS*1000;save('-attempt',attempt);showQuestion()}locked=false}
function startClock(){clearInterval(clockID);tick();if(attempt)clockID=setInterval(tick,200)}
function updateTimer(){if(!attempt||!$('#timer'))return;const left=Math.max(0,Math.ceil((attempt.deadline-Date.now())/1000));$('#timer').textContent=`${left} с`;$('#timer').classList.toggle('urgent',left<=10)}
function tick(){if(!attempt)return;let changed=false;while(attempt&&Date.now()>=attempt.deadline){attempt.answers.push(-1);lastTimedOut=true;changed=true;if(attempt.answers.length===10){finish();return}attempt.deadline+=SECONDS*1000}if(changed){save('-attempt',attempt);showQuestion()}updateTimer()}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick()});
function scoreOf(r){return r.answers.reduce((sum,a,i)=>sum+(a===QUESTIONS[i].correct?1:0),0)}
function gradeOf(score){return score>=9?5:score>=7?4:score>=5?3:2}
function finish(){clearInterval(clockID);result={first:attempt.first,last:attempt.last,answers:[...attempt.answers],completedAt:Date.now()};save('-result',result);attempt=null;remove('-attempt');render();$('#announcer').textContent=`Тест завершён. ${scoreOf(result)} баллов из 10. Оценка ${gradeOf(scoreOf(result))}.`}
function showResult(){const score=scoreOf(result),grade=gradeOf(score);$('#quiz').innerHTML=`<p class="eyebrow">Самопроверка завершена</p><h2>Твой результат</h2><div class="result-card" id="result-card"><p class="eyebrow">Информатика / 11 класс</p><h3>Сервисы Интернета</h3><p class="student">${escapeHTML(result.first)} ${escapeHTML(result.last)}</p><div class="result-numbers"><div><strong>${score}<small style="font-size:1.3rem;color:white"> / 10</small></strong><span>баллов</span></div><div><strong>${grade}</strong><span>оценка</span></div></div><p class="result-date">${new Date(result.completedAt).toLocaleString('ru-RU')} · Самопроверка</p></div><p class="fine" id="saved-notice">${storageOK?'Результат сохранён в этом браузере на этом устройстве.':'Браузер не разрешил сохранить результат. Скачай PNG, чтобы не потерять оценку.'}</p><div class="result-actions"><button class="button primary" id="share-result">Поделиться результатом с учителем</button><button class="button secondary" id="retry">Пройти ещё раз</button></div><p class="fine">Кнопка скачает PNG-карточку и откроет MAX в новой вкладке. Прикрепи скачанный файл в открывшемся окне.</p><p id="share-status" role="status" class="fine"></p><div id="share-fallback" hidden><a id="png-link" class="button secondary">Скачать PNG ещё раз</a> <a class="button secondary" href="${MAX_URL}" target="_blank" rel="noopener noreferrer">Открыть MAX</a></div><details class="result-review"><summary>Разбор ответов</summary>${QUESTIONS.map((q,i)=>`<div class="review-item"><strong>${i+1}. ${q.q}</strong><p>${result.answers[i]===-1?'Время истекло. Ответ не дан.':`Твой ответ: ${escapeHTML(q.a[result.answers[i]])}`}</p><p class="${result.answers[i]===q.correct?'correct':'error'}">${result.answers[i]===q.correct?'Верно · 1 балл':'0 баллов'}</p><p>${q.explain}</p><p class="fine">Источник: ${q.source}.</p><button class="button secondary" data-review="${q.slide}">Повторить тему</button></div>`).join('')}</details>`;$('#share-result').addEventListener('click',share);$('#retry').addEventListener('click',()=>{result=null;remove('-result');showStart();$('#first-name').focus()});$('#quiz').querySelectorAll('[data-review]').forEach(b=>b.addEventListener('click',()=>go(Number(b.dataset.review))))}
function resultPNG(r){const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=780;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');ctx.fillStyle='#f0f5f2';ctx.fillRect(0,0,1200,780);ctx.fillStyle='#173c35';ctx.fillRect(35,35,1130,710);ctx.fillStyle='#f6db75';ctx.font='bold 24px Arial';ctx.fillText('ИНФОРМАТИКА / 11 КЛАСС',80,102);ctx.fillStyle='#ffffff';ctx.font='bold 49px Arial';ctx.fillText('Сервисы Интернета',80,178);ctx.font='36px Arial';const lines=[];for(const name of [r.first,r.last]){let line='';for(const char of name){if(ctx.measureText(line+char).width>1030){lines.push(line);line=char}else line+=char}lines.push(line)}let y=248;for(const line of lines){ctx.fillText(line,80,y);y+=44}const score=scoreOf(r);ctx.fillStyle='#f6db75';ctx.font='bold 104px Arial';ctx.fillText(`${score} / 10`,80,510);ctx.fillText(`${gradeOf(score)}`,710,510);ctx.fillStyle='#ffffff';ctx.font='28px Arial';ctx.fillText('баллов',83,552);ctx.fillText('оценка',713,552);ctx.fillStyle='#dce8e2';ctx.font='23px Arial';ctx.fillText(new Date(r.completedAt).toLocaleString('ru-RU'),80,635);ctx.fillText('Самопроверка · 10 вопросов · 30 секунд на вопрос',80,684);return canvas.toDataURL('image/png')}
function share(){try{const url=resultPNG(result),a=document.createElement('a');a.href=url;a.download=`Результат_${result.last}_${result.first}.png`;document.body.appendChild(a);a.click();a.remove();const fallback=$('#png-link');fallback.href=url;fallback.download=`Результат_${result.last}_${result.first}.png`;$('#share-fallback').hidden=false;const opened=window.open(MAX_URL,'_blank');if(opened)opened.opener=null;$('#share-status').textContent='PNG подготовлен, скачивание запрошено. Если браузер не сохранил файл или не открыл MAX, используй кнопки ниже.'}catch{$('#share-status').textContent='Не удалось сформировать PNG. Попробуй ещё раз или сделай скриншот карточки результата.'}}
fromHash();
